
#' Interpolate GSOD Data to a Gridded Surface
#'
#' This function is designed to be wrapped in an \code{\link[base]{lapply}}
#' function to retrieve multiple years of GSOD data for interpolation, though a
#' single year may be used.
#'
#' @param bz2_file A bz2 CSV file generated by \link{fetch_gsod}.
#' @param dem Path to a raster readable digital elevation model file.
#' @param dsn where resulting CSV files are to be saved. Defaults
#' to user's "home" directory.
#'
#' @return
#' GeoTIFF files of interpolated GSOD data at the spatial resolution of the
#' supplied digital elevation model.
#'
#' @export
#'
#' @examples
#' \dontrun{
#' dem <- raster::raster("~/Data/SRTM/SRTM_1deg.grd")
#' # Run the function
#' lapply(X = GSOD_list, FUN = interp, dem = dem)
#' }

interpolate_gsod <- function(bz2_file, dem, dsn) {

  dsn <- .validate_dsn(dsn)

  # import the file for interpolation
  GSOD <- readr::read_csv(bz2_file, col_types = "cdddcddddd")

  for (i in unique(GSOD$YDAY)) {

    # subset the dataframe to just the date of interest
    x <- dplyr::filter(GSOD, rlang::.data$YDAY == i)

    for (j in c("TEMP", "MAX", "MIN", "RH")) {
      # create object with x, y and weather var
      y <- data.frame(x["LON"], x["LAT"], x["ELEV_M_SRTM_90m"], x[j])

      # remove any NA values from the data, the interpolation will not work with
      # any NAs present for any field.
      y <- stats::na.omit(y)

      # remove outliers
      bxs <- grDevices::boxplot.stats(y[, 4])
      y <- y[!y[, 4] %in% bxs$out, ]

      # create correction dataset
      y_vals <- y[, 4]
      names(y_vals) <- NULL

      # create thin plate spline object
      tps_y <- fields::Tps(y[, c("LON", "LAT", "ELEV_M_SRTM_90m")],
                           y_vals, lon.lat = TRUE)

      # interpolate thin plate spline object and write to disk
      tps_pred <- raster::interpolate(dem, tps_y, xyOnly = FALSE)

      raster::writeRaster(
        tps_pred,
        filename = paste0(dsn, "_", x[1, 5], "_", i, ".tiff"),
        format = "GTiff",
        dataType = "INT2S",
        options = c("COMPRESS=LZW", "TFW=YES"),
        overwrite = TRUE
      )
      gc()
    }
  }
}
